sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=anchal72
    - REGISTRY_PASS=harshita#070299
script:
  - docker build -t anchal72/webserver .
  - docker run -it anchal72/webserver

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push anchal72/webserver
  on:
    branch: master
